package picker

type AggKind string

const (
	AggKindAdjacencyMatrix           AggKind = "adjacency_matrix"
	AggKindAutoIntervalDateHistogram AggKind = "auto_date_histogram"
	AggKindChildren                  AggKind = "children"
	AggKindComposite                 AggKind = "composite"
	AggKindDateHistogram             AggKind = "date_histogram"
	AggKindDateRange                 AggKind = "date_range"
	AggKindDiversifiedSampler        AggKind = "diversified_sampler"
	AggKindFilter                    AggKind = "filter"
	AggKindFilters                   AggKind = "filters"
	AggKindGeoDistance               AggKind = "geo_distance"
	AggKindGeohashGrid               AggKind = "geohash_grid"
	AggKindGeotileGrid               AggKind = "geotile_grid"
	AggKindGlobal                    AggKind = "global"
	AggKindHistogram                 AggKind = "histogram"
	AggKindIPPange                   AggKind = "ip_range"
	AggKindMissing                   AggKind = "missing"
	AggKindMultiTerms                AggKind = "multi_terms"
	AggKindNested                    AggKind = "nested"
	AggKindParent                    AggKind = "parent"
	AggKindRange                     AggKind = "range"
	AggKindRareTerms                 AggKind = "rare_terms"
	AggKindReverseNested             AggKind = "reverse_nested"
	AggKindSampler                   AggKind = "sampler"
	AggKindSignificantTerms          AggKind = "significant_terms"
	AggKindSignificantText           AggKind = "significant_text"
	AggKindTerms                     AggKind = "terms"
	AggKindVariableWidthHistogram    AggKind = "variable_width_histogram"
	AggKindAvg                       AggKind = "avg"
	AggKindBoxplot                   AggKind = "boxplot"
	AggKindCardinality               AggKind = "cardinality"
	AggKindExtendedStats             AggKind = "extended_stats"
	AggKindGeoBounds                 AggKind = "geo_bounds"
	AggKindGeoCentroid               AggKind = "geo_centroid"
	AggKindGeoLine                   AggKind = "geo_line"
	AggKindMatrixStats               AggKind = "matrix_stats"
	AggKindMax                       AggKind = "max"
	AggKindMedianAbsoluteDeviation   AggKind = "median_absolute_deviation"
	AggKindMin                       AggKind = "min"
	AggKindPercentileRanks           AggKind = "percentile_ranks"
	AggKindPercentiles               AggKind = "percentiles"
	AggKindRate                      AggKind = "rate"
	AggKindScriptedMetric            AggKind = "metric"
	AggKindStats                     AggKind = "stats"
	AggKindStringStats               AggKind = "string_stats"
	AggKindSum                       AggKind = "sum"
	AggKindTTest                     AggKind = "t_test"
	AggKindTopHits                   AggKind = "top_hits"
	AggKindTopMetrics                AggKind = "top_metrics"
	AggKindValueCount                AggKind = "value_count"
	AggKindWeightedAvg               AggKind = "weighted_avg"
	AggKindAverageBucket             AggKind = "avg_bucket"
	AggKindBucketScript              AggKind = "bucket_script"
	AggKindBucketSelector            AggKind = "bucket_selector"
	AggKindBucketSort                AggKind = "bucket_sort"
	AggKindCumulativeCardinality     AggKind = "cumulative_cardinality"
	AggKindCumulativeSum             AggKind = "cumulative_sum"
	AggKindDerivative                AggKind = "derivative"
	AggKindExtendedStatsBucket       AggKind = "extended_stats_bucket"
	AggKindInferenceBucket           AggKind = "inference"
	AggKindMaxBucket                 AggKind = "max_bucket"
	AggKindMinBucket                 AggKind = "min_bucket"
	AggKindMovingAverage             AggKind = "moving_avg"
	AggKindMovingFunction            AggKind = "moving_fn"
	AggKindMovingPercentiles         AggKind = "moving_percentiles"
	AggKindNormalize                 AggKind = "normalize"
	AggKindPercentilesBucket         AggKind = "percentiles_bucket"
	AggKindSerialDifferencing        AggKind = "serial_diff"
	AggKindStatsBucket               AggKind = "stats_bucket"
	AggKindSumBucket                 AggKind = "sum_bucket"
)

// Subtleties of bucketing range fields
